name: PR Checks
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

jobs:
  pr-checks:
    name: pr-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun check
      - run: bun typecheck
      - run: bun run build
